# Generated by Django 5.2.8 on 2026-01-04 14:17

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_image', models.URLField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True)),
                ('weight', models.FloatField(blank=True, help_text='kg', null=True)),
                ('height', models.IntegerField(blank=True, help_text='cm', null=True)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('preferred_distance', models.CharField(blank=True, choices=[('5K', '5K'), ('10K', '10K'), ('half_marathon', 'Half Marathon'), ('marathon', 'Marathon')], max_length=20, null=True)),
                ('current_max_distance', models.FloatField(default=0.0, help_text='Tek seferde koşulan maksimum mesafe (km)')),
                ('current_pace', models.IntegerField(default=360, help_text='Ortalama tempo (saniye/km). Örn: 360 saniye = 6:00 dk/km')),
                ('weekly_goal', models.IntegerField(default=3, help_text='Haftalık hedeflenen antrenman sayısı')),
                ('total_workouts', models.IntegerField(default=0)),
                ('total_distance', models.FloatField(default=0.0)),
                ('total_time', models.IntegerField(default=0, help_text='Dakika cinsinden toplam süre')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('push_token', models.CharField(blank=True, max_length=255, null=True)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('preferred_reminder_time', models.TimeField(default='09:00:00', help_text='Günlük hatırlatma saati')),
                ('notification_workout_reminder', models.BooleanField(default=True)),
                ('notification_weekly_report', models.BooleanField(default=True)),
                ('notification_achievements', models.BooleanField(default=True)),
                ('notification_plan_updates', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('achievement_type', models.CharField(choices=[('distance', 'Mesafe Rozeti'), ('workout_count', 'Antrenman Sayısı'), ('streak', 'Seri Rozeti'), ('pace', 'Hız Rozeti'), ('completion', 'Tamamlama Rozeti'), ('special', 'Özel Rozet')], max_length=50)),
                ('icon_name', models.CharField(default='trophy', max_length=50)),
                ('icon_color', models.CharField(default='#FFD700', max_length=20)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Örn: 10K Hazırlık - Hız Odaklı', max_length=255)),
                ('description', models.TextField(blank=True, help_text='AI tarafından oluşturulan plan özeti')),
                ('goal', models.CharField(help_text="Örn: 10K'yı 50 dakika altında koşmak", max_length=255)),
                ('start_date', models.DateField(help_text='Planın başladığı gün')),
                ('end_date', models.DateField(help_text='Planın biteceği gün')),
                ('duration_weeks', models.IntegerField(help_text='Plan kaç hafta sürüyor?')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20)),
                ('workouts_per_week', models.IntegerField(help_text='Haftalık antrenman sayısı')),
                ('total_workouts_count', models.IntegerField(default=0)),
                ('completed_workouts_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('ai_generated', models.BooleanField(default=True)),
                ('ai_conversation_history', models.JSONField(blank=True, default=list, help_text='LangGraph/Chat history')),
                ('ai_parameters', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('workout_type', models.CharField(choices=[('tempo', 'Tempo Run'), ('easy', 'Easy Run'), ('interval', 'Intervals'), ('long', 'Long Run'), ('rest', 'Rest Day')], max_length=20)),
                ('scheduled_date', models.DateField()),
                ('planned_distance', models.FloatField(default=0.0, help_text='km')),
                ('planned_duration', models.IntegerField(default=0, help_text='dakika')),
                ('target_pace_seconds', models.IntegerField(blank=True, help_text='Hedef saniye/km', null=True)),
                ('day_of_week', models.IntegerField(blank=True, help_text='0=Pazartesi... Otomatik hesaplanır', null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('missed', 'Missed')], default='scheduled', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workouts', to='core.program')),
            ],
            options={
                'ordering': ['scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('reminder', 'Hatırlatıcı'), ('achievement', 'Tebrikler'), ('system', 'Sistem/AI'), ('info', 'Bilgi')], max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('related_program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.program')),
                ('related_workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workout')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actual_distance', models.FloatField(help_text='Koşulan mesafe (km)')),
                ('actual_duration', models.IntegerField(help_text='Koşulan süre (dakika)')),
                ('actual_pace_seconds', models.IntegerField(default=0, help_text='Ortalama pace (sn/km)')),
                ('calories_burned', models.IntegerField(default=0, help_text='O anki kiloya göre hesaplanan kalori')),
                ('feeling', models.CharField(choices=[('hard', 'Zor/Kötü'), ('normal', 'Normal'), ('easy', 'Kolay/İyi')], default='normal', max_length=10)),
                ('user_notes', models.TextField(blank=True, help_text='Kullanıcının kısa notları')),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to=settings.AUTH_USER_MODEL)),
                ('workout', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='result', to='core.workout')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
