# Generated by Django 5.2.8 on 2026-01-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='ai_conversation_history',
        ),
        migrations.RemoveField(
            model_name='program',
            name='ai_generated',
        ),
        migrations.RemoveField(
            model_name='program',
            name='ai_parameters',
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='duration_weeks',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='program',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='program',
            name='goal',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='program',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='program',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('completed', 'Completed')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='program',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='program',
            name='workouts_per_week',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_max_distance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='current_pace',
            field=models.IntegerField(default=360, help_text='Saniye/km'),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_reminder_time',
            field=models.TimeField(default='09:00:00'),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='weekly_goal',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='workout',
            name='day_of_week',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='planned_distance',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='workout',
            name='planned_duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workout',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('missed', 'Missed')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='workout',
            name='target_pace_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_type',
            field=models.CharField(choices=[('tempo', 'Tempo Run'), ('easy', 'Easy Run'), ('interval', 'Intervals'), ('long', 'Long Run')], max_length=20),
        ),
        migrations.AlterField(
            model_name='workoutresult',
            name='actual_distance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='workoutresult',
            name='actual_duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='workoutresult',
            name='actual_pace_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workoutresult',
            name='calories_burned',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workoutresult',
            name='feeling',
            field=models.CharField(choices=[('hard', 'Zor'), ('normal', 'Normal'), ('easy', 'Kolay')], default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='workoutresult',
            name='user_notes',
            field=models.TextField(blank=True),
        ),
    ]
