# Generated by Django 6.0.1 on 2026-02-21 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_current_max_distance_user_max_runned_distance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='weekly_goal',
        ),
    ]
