# Generated by Django 6.0.1 on 2026-03-21 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_is_onboarded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_pace',
            field=models.IntegerField(blank=True, default=540, help_text='Saniye/km', null=True),
        ),
    ]
