# Generated by Django 6.0.1 on 2026-03-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_has_completed_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='has_completed_tour',
        ),
        migrations.AddField(
            model_name='user',
            name='completed_tours',
            field=models.JSONField(blank=True, default=dict, help_text='Örn: {"home": true, "calendar": true, "plans": true, "profile": true}'),
        ),
    ]
