# Generated by Django 6.0.1 on 2026-01-25 09:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('achievement_type', models.CharField(choices=[('distance', 'Mesafe Rozeti'), ('workout_count', 'Antrenman Sayısı'), ('streak', 'Seri Rozeti'), ('pace', 'Hız Rozeti'), ('completion', 'Tamamlama Rozeti'), ('special', 'Özel Rozet')], max_length=50)),
                ('icon_name', models.CharField(default='trophy', max_length=50)),
                ('icon_color', models.CharField(default='#FFD700', max_length=20)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-earned_at'],
            },
        ),
    ]
