# Generated by Django 6.0.1 on 2026-02-21 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_remove_program_difficulty_program_running_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='workouts_per_week',
        ),
    ]
