# Generated by Django 6.0.1 on 2026-03-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_remove_program_workouts_per_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
