# Generated by Django 6.0.1 on 2026-02-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='current_max_distance',
            new_name='max_runned_distance',
        ),
        migrations.RemoveField(
            model_name='user',
            name='experience_level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_distance',
        ),
        migrations.AddField(
            model_name='user',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_reschedule_reset',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_running_days',
            field=models.JSONField(blank=True, default=list, help_text='Örn: [0, 2, 4] (0=Pzt, 6=Paz)'),
        ),
        migrations.AddField(
            model_name='user',
            name='reschedules_used_this_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_tokens_used',
            field=models.IntegerField(default=0, help_text='Chatbot token kullanımı'),
        ),
    ]
