# Generated by Django 6.0.1 on 2026-02-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_weekly_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_pace',
            field=models.IntegerField(blank=True, default=480, help_text='Saniye/km', null=True),
        ),
    ]
