# Generated by Django 6.0.1 on 2026-03-21 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_current_pace'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='premium_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='premium_type',
            field=models.CharField(blank=True, choices=[('monthly', 'Aylık'), ('yearly', 'Yıllık')], max_length=10, null=True),
        ),
    ]
