# Generated by Django 6.0.1 on 2026-03-22 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_current_pace'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_completed_tour',
            field=models.BooleanField(default=False),
        ),
    ]
