# Generated by Django 6.0.1 on 2026-03-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_user_has_completed_tour_user_completed_tours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='completed_tours',
        ),
        migrations.AddField(
            model_name='user',
            name='tour_calendar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='tour_home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='tour_plans',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='tour_profile',
            field=models.BooleanField(default=False),
        ),
    ]
