# Generated by Django 6.0.1 on 2026-04-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_user_completed_tours_user_tour_calendar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='original_transaction_id',
            field=models.CharField(blank=True, db_index=True, help_text="Apple/Google'ın değişmez transaction ID'si — refund/dispute referansı", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='premium_last_verified_at',
            field=models.DateTimeField(blank=True, help_text="Webhook veya REST ile state'in son doğrulandığı zaman (debug için)", null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='premium_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='premium_will_renew',
            field=models.BooleanField(default=True, help_text='Auto-renew açık mı? Cancel edilince false olur'),
        ),
        migrations.AddField(
            model_name='user',
            name='rc_app_user_id',
            field=models.CharField(blank=True, db_index=True, help_text="RevenueCat app_user_id — Django user.id'nin string hali", max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='store',
            field=models.CharField(blank=True, choices=[('app_store', 'App Store'), ('play_store', 'Play Store')], max_length=20, null=True),
        ),
    ]
