# Generated by Django 6.0.1 on 2026-02-21 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='difficulty',
        ),
        migrations.AddField(
            model_name='program',
            name='running_days',
            field=models.JSONField(blank=True, default=list, help_text='Örn: [0, 2, 4]'),
        ),
    ]
