# Generated by Django 6.0.1 on 2026-01-25 09:01

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actual_distance', models.FloatField()),
                ('actual_duration', models.IntegerField()),
                ('actual_pace_seconds', models.IntegerField(default=0)),
                ('calories_burned', models.IntegerField(default=0)),
                ('feeling', models.CharField(choices=[('hard', 'Zor'), ('normal', 'Normal'), ('easy', 'Kolay')], default='normal', max_length=10)),
                ('user_notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
